# -*- coding: utf-8 -*-
"""
Nombre del Módulo: protocols.py (Product)
Descripción: Define los protocolos (interfaces estructurales) para garantizar el 
             tipado correcto y la compatibilidad entre el controlador de productos y sus gestores.
"""
from __future__ import annotations
from typing import Protocol, Any, Dict, List, Optional, Tuple, TYPE_CHECKING
import logging

if TYPE_CHECKING:
    from core.application_state import ApplicationState
    from core.dtos import (
        ProductDTO, FabricacionDTO, PreprocesoDTO, 
        MaterialDTO, SubfabricacionDTO, ProcesoMecanicoDTO,
        FabricacionProductoDTO, ProductDetailsDTO
    )

class IProductView(Protocol):
    """Protocolo para la interfaz de usuario de productos."""
    pages: Dict[str, Any]
    
    def get_products_tab(self) -> Any: ...
    def get_fabrications_tab(self) -> Any: ...
    def get_page(self, name: str) -> Any: ...
    def show_message(self, title: str, message: str, level: str = "info") -> None: ...
    def show_confirmation_dialog(self, title: str, message: str) -> bool: ...
    def get_iteration_tab(self) -> Any: ...
    def get_materials_details_page(self) -> Any: ...
    def get_main_tab_widget(self) -> Any: ...

class IProductService(Protocol):
    """Protocolo para el servicio de productos."""
    def search_products(self, text: str) -> List[Any]: ...
    def get_product_by_code(self, codigo: str) -> Optional[Any]: ...
    def get_product_details(self, product_code: str) -> ProductDetailsDTO: ...
    def add_product(self, data: Dict[str, Any], sub_partes: List[Dict[str, Any]]) -> str: ...
    def update_product(self, original_codigo: str, new_data: Dict[str, Any], sub_fabricaciones: List[Dict[str, Any]]) -> bool: ...
    def delete_product(self, codigo: str) -> bool: ...
    def add_product_iteration(self, product_code: str, responsable: str, descripcion: str, tipo_fallo: str, extras: List[Any], date: Optional[Any]) -> Optional[int]: ...
    def update_product_iteration(self, iteracion_id: int, responsable: str, descripcion: str, tipo_fallo: str) -> bool: ...
    def delete_product_iteration(self, iteration_id: int) -> bool: ...
    def add_iteration_image(self, iteration_id: int, final_path: str) -> bool: ...
    def get_product_iterations_by_id_or_similar(self, iteration_id: int) -> Any: ...
    def update_iteration_file_path(self, iteracion_id: int, field: str, path: str) -> bool: ...
    def delete_iteration_image(self, image_id: int) -> bool: ...

class IFabricacionService(Protocol):
    """Protocolo para el servicio de fabricaciones."""
    def search_fabricaciones(self, query: str) -> List[FabricacionDTO]: ...
    def get_fabricacion_by_id(self, fabricacion_id: int) -> Optional[FabricacionDTO]: ...
    def get_fabricacion_by_codigo(self, codigo: str) -> Optional[FabricacionDTO]: ...
    def create_fabricacion_with_preprocesos(self, data: FabricacionDTO) -> bool: ...
    def update_fabricacion_and_preprocesos(
        self, fabricacion_id: int, data: FabricacionDTO, preproceso_ids: List[int] | None = None
    ) -> bool: ...
    def delete_fabricacion(self, fabricacion_id: int) -> bool: ...
    def get_all_preprocesos_with_components(self) -> List[PreprocesoDTO]: ...
    def get_preprocesos_by_fabricacion(self, fabricacion_id: int) -> List[PreprocesoDTO]: ...
    def update_fabricacion_preprocesos(self, fabricacion_id: int, preproceso_ids: List[int]) -> bool: ...
    def get_products_for_fabricacion(self, fabricacion_id: int) -> List[FabricacionProductoDTO]: ...
    def set_products_for_fabricacion(self, fabricacion_id: int, products_data: List[FabricacionProductoDTO]) -> bool: ...
    def create_preproceso(self, data: PreprocesoDTO) -> bool: ...
    def update_preproceso(self, preproceso_id: int, data: PreprocesoDTO) -> bool: ...
    def delete_preproceso(self, preproceso_id: int) -> bool: ...

class IMaterialService(Protocol):
    """Protocolo para el servicio de materiales."""
    def import_materials_to_product(self, product_code: str, file_path: str) -> bool: ...
    def add_material_to_product(self, product_code: str, material_code: str, material_desc: str) -> bool: ...
    def update_material(self, material_id: int, new_code: str, new_desc: str) -> bool: ...
    def unlink_material_from_product(self, product_code: str, material_id: int) -> bool: ...
    def create_material(self, code: str, desc: str) -> bool: ...
    def delete_material(self, material_id: int) -> bool: ...
    def get_all_materials_for_selection(self) -> List[Any]: ...
    def add_material(self, code: str, desc: str) -> Optional[int]: ...
    def link_material_to_product(self, product_code: str, material_id: int) -> bool: ...

class IProductModel(Protocol):
    """Protocolo para el modelo de datos de productos."""
    product_facade: Any
    planning_facade: Any
    product_service: IProductService
    fabricacion_service: IFabricacionService
    material_service: IMaterialService
    machine_service: Any
    
    def search_products(self, text: str) -> List[Any]: ...
    def get_fabrication_products_for_calculation(self, fabricacion_id: int) -> List[Dict[str, Any]]: ...
    def get_data_for_calculation(self, product_code: str) -> List[Dict[str, Any]]: ...
    def get_all_preprocesos_with_components(self) -> List[Any]: ...
    def update_iteration_file_path(self, iteration_id: int, key: str, final_path: str) -> bool: ...
    def get_product_iterations(self, codigo_producto: str) -> List[Any]: ...

class ProductControllerProtocol(Protocol):
    """Contrato estructural que cumple ProductController (vista, servicios, estado, callbacks)."""
    app: Any
    db: Any
    model: IProductModel
    view: IProductView
    logger: logging.Logger
    state: ApplicationState 
    product_facade: Any
    product_service: IProductService
    material_service: IMaterialService
    fabricacion_service: IFabricacionService
    ui_controller: Any

    def _on_product_search_changed(self, text: str) -> None: ...
    def _on_product_result_selected(self, item: Any) -> None: ...
    def _on_manage_subs_clicked(self) -> None: ...
    def _on_manage_details_clicked(self, product_code: str) -> None: ...
    def _on_manage_procesos_clicked(self) -> None: ...
    def _on_update_product(self, original_codigo: str) -> None: ...
    def _on_delete_product(self, codigo: str) -> None: ...
    def _load_preprocesos_data(self) -> None: ...
    def _refresh_fabricaciones_list(self) -> None: ...
    def _on_fabrication_search_changed(self, text: str) -> None: ...
    def _on_fabrication_result_selected_by_id(self, fabricacion_id: int) -> None: ...
    def handle_add_iteration_image(self, iteration_id: int, file_path: str) -> Tuple[bool, str]: ...
    def on_data_changed(self) -> None: ...
