# -*- coding: utf-8 -*-
"""
Paquete: controllers.worker
Descripción: Controladores y gestores para la administración de trabajadores e interfaz de operario.
"""
"""
Nombre del Módulo: protocols.py (Worker)
Descripción: Define las interfaces estructurales para los componentes del sub-paquete Worker.
"""
from typing import Protocol, Any, List, Optional, Dict, Tuple
import logging

class IWorkerView(Protocol):
    """Interfaz para las operaciones de UI requeridas por el dominio Worker."""
    pages: Dict[str, Any]
    def show_message(self, title: str, message: str, type: str = "info") -> None: ...
    def show_confirmation_dialog(self, title: str, message: str) -> bool: ...
    # Métodos delegados a widgets internos (pueden ser mocks en el controlador fachada)
    def update_workers_list(self, workers: List[Dict[str, Any]]) -> None: ...
    def show_worker_details(self, worker_data: Dict[str, Any]) -> None: ...
    def clear_worker_details(self) -> None: ...
    def update_tasks_list(self, tasks: List[Dict[str, Any]]) -> None: ...
    def update_task_state(self, task_id: int, state: str) -> None: ...
    def show_worker_password_dialog(self, worker_name: str) -> Tuple[bool, Optional[str]]: ...
    def update_product_search_results(self, results: List[Any]) -> None: ...
    def populate_history_tables(self, history: List[Dict[str, Any]], annotations: List[Dict[str, Any]]) -> None: ...
    def get_assignment_data(self) -> Dict[str, Any]: ...

class IWorkerService(Protocol):
    """Interfaz para el servicio de gestión de trabajadores."""
    def get_worker_details(self, worker_id: int) -> Optional[Dict[str, Any]]: ...
    def update_user_password(self, user_id: int, new_password: str) -> bool: ...
    def authenticate_user(self, username: str, password: str) -> Optional[Dict[str, Any]]: ...
    def add_worker(self, nombre: str, notas: str, tipo: int, username: Optional[str], password_hash: Optional[str], role: Optional[str]) -> Any: ...
    def update_worker(self, worker_id: int, nombre: str, activo: bool, notas: str, tipo: int, username: Optional[str], password_hash: Optional[str], role: Optional[str]) -> bool: ...
    def delete_worker(self, worker_id: int) -> bool: ...
    def get_all_workers(self) -> List[Dict[str, Any]]: ...
    def assign_task_to_worker(self, worker_id: int, product_code: str, quantity: float) -> Tuple[bool, str]: ...
    def actualizar_estado_asignacion(self, trabajador_id: int, fabricacion_id: int, nuevo_estado: str) -> bool: ...
    def get_worker_history(self, worker_id: int) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]: ...
    def get_worker_tasks(self, worker_id: int) -> List[Dict[str, Any]]: ...
    def start_task(self, worker_id: int, task_id: int) -> bool: ...

class IFabricacionService(Protocol):
    """Interfaz para servicios de fabricación."""
    def get_all_ordenes_fabricacion(self) -> List[str]: ...

class IProductService(Protocol):
    """Interfaz para servicios de producto."""
    def search_products(self, text: str) -> List[Any]: ...

class IWorkerModel(Protocol):
    """Interfaz para el modelo que agrupa servicios de Worker."""
    worker_service: IWorkerService
    product_service: IProductService
    fabricacion_service: Optional[IFabricacionService]
    workers_changed_signal: Any

    def get_worker_history(self, worker_id: int) -> Tuple[List[Any], List[Any]]: ...
    def get_worker_activity_log(self, worker_id: int) -> List[Any]: ...

class WorkerControllerProtocol(Protocol):
    """Interfaz para el controlador fachada de Worker."""
    app: Any
    model: IWorkerModel
    view: IWorkerView
    logger: logging.Logger
    management_manager: Any
    
    def update_workers_view(self) -> None: ...
