# -*- coding: utf-8 -*-
"""Fachada de compatibilidad para DTOs de dominio.

`core.dtos` se mantiene como punto de import estable para todo el proyecto.
Las definiciones concretas viven en `core.dtos_models`.
"""
from __future__ import annotations

from core.dtos_models import (
    AuthResponseDTO,
    BackupInfoDTO,
    CameraConfigDTO,
    CameraDetailDTO,
    CanvasCyclicConnectionFlags,
    ComponenteDTO,
    ConfigurationDTO,
    FabricacionDTO,
    FabricacionProductoDTO,
    FlowCanvasTaskDTO,
    FlowItemDTO,
    FlowTaskConfigDTO,
    FlowTaskDataDTO,
    IterationImageDTO,
    LabelRangeDTO,
    LoteDTO,
    MachineDTO,
    MachineMaintenanceDTO,
    MaterialDTO,
    MaterialStatsDTO,
    PilaDTO,
    PreparationGroupDTO,
    PreparationStepDTO,
    PreprocesoDTO,
    CalculationSubPartDTO,
    CalculationProductDTO,
    ProcesoMecanicoDTO,
    ProductDTO,
    ProductFlowLibraryProductDTO,
    ProductIterationDTO,
    ProductIterationMaterialDTO,
    ProductionFlowStepDTO,
    SimulationResultTaskDTO,
    SubfabricacionDTO,
    WorkerAnnotationDTO,
    WorkerDTO,
    WorkerDetailDTO,
    FileOperationResultDTO,
    ProductDetailsDTO,
    QuoteDTO,
    AuthorInfoDTO,
    SyncRecordDTO,
    SyncRecordPayloadDTO,
    SyncTableDifferencesDTO,
    DatabaseComparisonDTO,
    WorkerFormDataDTO,
    LoteInstanceParametersDTO,
    CalculationStepDTO,
)

__all__ = [
    "MachineDTO",
    "MachineMaintenanceDTO",
    "PreparationGroupDTO",
    "PreparationStepDTO",
    "WorkerDTO",
    "WorkerAnnotationDTO",
    "WorkerDetailDTO",
    "AuthResponseDTO",
    "BackupInfoDTO",
    "SimulationResultTaskDTO",
    "CalculationSubPartDTO",
    "CalculationProductDTO",
    "ProductDTO",
    "SubfabricacionDTO",
    "ProcesoMecanicoDTO",
    "MaterialDTO",
    "PilaDTO",
    "MaterialStatsDTO",
    "ComponenteDTO",
    "FabricacionProductoDTO",
    "PreprocesoDTO",
    "FabricacionDTO",
    "LoteDTO",
    "ConfigurationDTO",
    "ProductIterationMaterialDTO",
    "ProductIterationDTO",
    "LabelRangeDTO",
    "IterationImageDTO",
    "FlowTaskDataDTO",
    "FlowTaskConfigDTO",
    "CanvasCyclicConnectionFlags",
    "ProductFlowLibraryProductDTO",
    "ProductionFlowStepDTO",
    "FlowCanvasTaskDTO",
    "FlowItemDTO",
    "CameraConfigDTO",
    "CameraDetailDTO",
    "FileOperationResultDTO",
    "ProductDetailsDTO",
    "QuoteDTO",
    "AuthorInfoDTO",
    "SyncRecordDTO",
    "SyncRecordPayloadDTO",
    "SyncTableDifferencesDTO",
    "DatabaseComparisonDTO",
    "CalculationStepDTO",
]
