"""Initial clean migration

Revision ID: c1444b2546d3
Revises: 
Create Date: 2026-02-07 11:21:28.029952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1444b2546d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('fabricaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('departamento', sa.String(), nullable=False),
    sa.Column('tipo_proceso', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_componente', sa.String(), nullable=False),
    sa.Column('descripcion_componente', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_componente')
    )
    op.create_table('preprocesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tiempo', sa.Float(), nullable=False),
    sa.Column('tipo_trabajador', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('departamento', sa.String(), nullable=False),
    sa.Column('tipo_trabajador', sa.Integer(), nullable=False),
    sa.Column('donde', sa.String(), nullable=True),
    sa.Column('tiene_subfabricaciones', sa.Boolean(), nullable=False),
    sa.Column('tiempo_optimo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('tipo_trabajador', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_completo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fabricacion_contadores',
    sa.Column('fabricacion_id', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_unidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fabricacion_id'], ['fabricaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fabricacion_id')
    )
    op.create_table('fabricacion_preproceso_link',
    sa.Column('fabricacion_id', sa.Integer(), nullable=True),
    sa.Column('preproceso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fabricacion_id'], ['fabricaciones.id'], ),
    sa.ForeignKeyConstraint(['preproceso_id'], ['preprocesos.id'], )
    )
    op.create_table('fabricacion_productos',
    sa.Column('fabricacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fabricacion_id'], ['fabricaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fabricacion_id', 'producto_codigo')
    )
    op.create_table('grupos_preparacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('producto_codigo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iteraciones_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('nombre_responsable', sa.String(), nullable=False),
    sa.Column('descripcion_cambio', sa.Text(), nullable=True),
    sa.Column('ruta_imagen', sa.String(), nullable=True),
    sa.Column('tipo_fallo', sa.String(), nullable=True),
    sa.Column('ruta_plano', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_fabricacion_link',
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fabricacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fabricacion_id'], ['fabricaciones.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('lote_id', 'fabricacion_id')
    )
    op.create_table('lote_producto_link',
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ),
    sa.PrimaryKeyConstraint('lote_id', 'producto_codigo')
    )
    op.create_table('machine_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['maquinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('resultados_simulacion', sa.Text(), nullable=True),
    sa.Column('producto_origen_codigo', sa.String(), nullable=True),
    sa.Column('pila_de_calculo_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['producto_origen_codigo'], ['productos.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('preproceso_material_link',
    sa.Column('preproceso_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['preproceso_id'], ['preprocesos.id'], )
    )
    op.create_table('procesos_mecanicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('tiempo', sa.Float(), nullable=False),
    sa.Column('tipo_trabajador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_material_link',
    sa.Column('producto_codigo', sa.String(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], )
    )
    op.create_table('subfabricaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('tiempo', sa.Float(), nullable=False),
    sa.Column('tipo_trabajador', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajador_fabricacion_link',
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fabricacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fabricacion_id'], ['fabricaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trabajador_id', 'fabricacion_id')
    )
    op.create_table('trabajo_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('orden_fabricacion', sa.String(), nullable=True),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('fabricacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(), nullable=False),
    sa.Column('tiempo_inicio', sa.DateTime(), nullable=False),
    sa.Column('tiempo_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fabricacion_id'], ['fabricaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabajo_logs_orden_fabricacion'), 'trabajo_logs', ['orden_fabricacion'], unique=False)
    op.create_index(op.f('ix_trabajo_logs_qr_code'), 'trabajo_logs', ['qr_code'], unique=True)
    op.create_table('diario_bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pila_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pila_id'], ['pilas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pila_id')
    )
    op.create_table('incidencia_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajo_log_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('tipo_incidencia', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabajo_log_id'], ['trabajo_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iteracion_material_link',
    sa.Column('iteracion_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['iteracion_id'], ['iteraciones_producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iteracion_id', 'material_id')
    )
    op.create_table('pasos_pila',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pila_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('datos_paso', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pila_id'], ['pilas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasos_trazabilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajo_log_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('paso_nombre', sa.String(), nullable=False),
    sa.Column('tipo_paso', sa.String(), nullable=True),
    sa.Column('tiempo_inicio_paso', sa.DateTime(), nullable=False),
    sa.Column('tiempo_fin_paso', sa.DateTime(), nullable=True),
    sa.Column('duracion_paso_segundos', sa.Integer(), nullable=True),
    sa.Column('estado_paso', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabajo_log_id'], ['trabajo_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasos_trazabilidad_trabajo_log_id'), 'pasos_trazabilidad', ['trabajo_log_id'], unique=False)
    op.create_table('preparacion_pasos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tiempo_fase', sa.Float(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('es_diario', sa.Boolean(), nullable=True),
    sa.Column('es_verificacion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_preparacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajador_pila_anotaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('pila_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('anotacion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pila_id'], ['pilas.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrada_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bitacora_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('dia_numero', sa.Integer(), nullable=False),
    sa.Column('plan_previsto', sa.Text(), nullable=True),
    sa.Column('trabajo_realizado', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bitacora_id'], ['diario_bitacora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencia_adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('tipo_mime', sa.String(), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencia_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidencia_adjuntos')
    op.drop_table('entrada_diario')
    op.drop_table('trabajador_pila_anotaciones')
    op.drop_table('preparacion_pasos')
    op.drop_index(op.f('ix_pasos_trazabilidad_trabajo_log_id'), table_name='pasos_trazabilidad')
    op.drop_table('pasos_trazabilidad')
    op.drop_table('pasos_pila')
    op.drop_table('iteracion_material_link')
    op.drop_table('incidencia_logs')
    op.drop_table('diario_bitacora')
    op.drop_index(op.f('ix_trabajo_logs_qr_code'), table_name='trabajo_logs')
    op.drop_index(op.f('ix_trabajo_logs_orden_fabricacion'), table_name='trabajo_logs')
    op.drop_table('trabajo_logs')
    op.drop_table('trabajador_fabricacion_link')
    op.drop_table('subfabricaciones')
    op.drop_table('producto_material_link')
    op.drop_table('procesos_mecanicos')
    op.drop_table('preproceso_material_link')
    op.drop_table('pilas')
    op.drop_table('machine_maintenance')
    op.drop_table('lote_producto_link')
    op.drop_table('lote_fabricacion_link')
    op.drop_table('iteraciones_producto')
    op.drop_table('grupos_preparacion')
    op.drop_table('fabricacion_productos')
    op.drop_table('fabricacion_preproceso_link')
    op.drop_table('fabricacion_contadores')
    op.drop_table('trabajadores')
    op.drop_table('productos')
    op.drop_table('preprocesos')
    op.drop_table('materiales')
    op.drop_table('maquinas')
    op.drop_table('lotes')
    op.drop_table('fabricaciones')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
