# -*- coding: utf-8 -*-
"""
Nombre del Módulo: core.protocols.domain

Descripción: Define protocolos o tipos principales: ``IProductService``, ``IFabricacionService``, ``IMaterialService``. Contrato del servicio de catálogo, iteraciones e imágenes de producto. Integración típica con: ``__future__``, ``core``.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol

from core.dtos import (
    FabricacionDTO,
    MaterialDTO,
    PreprocesoDTO,
    FabricacionProductoDTO,
    ProductDetailsDTO,
    ProductIterationDTO,
)


class IProductService(Protocol):
    """Contrato del servicio de catálogo, iteraciones e imágenes de producto."""

    def search_products(self, text: str) -> List[Any]: ...

    def get_latest_products(self, limit: int = 10) -> List[Any]: ...

    def get_product_by_code(self, codigo: str) -> Optional[Any]: ...

    def get_product_details(self, product_code: str) -> ProductDetailsDTO: ...

    def add_product(self, data: Dict[str, Any], sub_data: Optional[List[Any]] = None) -> str: ...

    def update_product(
        self, original_codigo: str, new_data: Dict[str, Any], subfabricaciones: Optional[List[Any]] = None
    ) -> bool: ...

    def delete_product(self, codigo: str) -> bool: ...

    def add_product_iteration(
        self,
        codigo_producto: str,
        responsable: str,
        descripcion: str,
        tipo_fallo: str,
        materiales_list: List[Dict[str, Any]],
        ruta_imagen: Optional[str] = None,
        ruta_plano: Optional[str] = None,
    ) -> Optional[int]: ...

    def update_product_iteration(
        self, iteracion_id: int, responsable: str, descripcion: str, tipo_fallo: str
    ) -> bool: ...

    def delete_product_iteration(self, iteration_id: int) -> bool: ...

    def add_iteration_image(self, iteration_id: int, image_path: str) -> bool: ...

    def get_product_iterations_by_id_or_similar(self, iteration_id: int) -> Any: ...

    def update_iteration_file_path(self, iteracion_id: int, column_name: str, file_path: str) -> bool: ...

    def delete_iteration_image(self, image_id: int) -> bool: ...

    def get_product_iterations(self, codigo_producto: str) -> List[ProductIterationDTO]: ...

    def get_materials_for_product(self, producto_codigo: str) -> List[MaterialDTO]: ...

    def add_material(self, codigo: str, descripcion: str) -> Optional[int]: ...

    def link_material_to_product(self, producto_codigo: str, material_id: int) -> bool: ...


class IFabricacionService(Protocol):
    """Contrato del servicio de fabricaciones y preprocesos."""

    def get_latest_fabricaciones(self, limit: int = 5) -> List[Any]: ...

    def create_fabricacion(self, codigo: str, descripcion: str) -> bool: ...

    def search_fabricaciones(self, query: str) -> List[Any]: ...

    def get_fabricacion_by_id(self, fabricacion_id: int) -> Any: ...

    def get_fabricacion_by_codigo(self, codigo: str) -> Any: ...

    def create_fabricacion_with_preprocesos(self, data: FabricacionDTO) -> bool: ...

    def update_fabricacion_and_preprocesos(
        self, fabricacion_id: int, data: FabricacionDTO, preproceso_ids: Optional[List[int]] = None
    ) -> bool: ...

    def delete_fabricacion(self, fabricacion_id: int) -> bool: ...

    def get_all_preprocesos_with_components(self) -> List[PreprocesoDTO]: ...

    def get_preprocesos_by_fabricacion(self, fabricacion_id: int) -> List[Any]: ...

    def update_fabricacion_preprocesos(self, fabricacion_id: int, preproceso_ids: List[int]) -> bool: ...

    def get_products_for_fabricacion(self, fabricacion_id: int) -> List[FabricacionProductoDTO]: ...

    def set_products_for_fabricacion(
        self, fabricacion_id: int, productos: List[FabricacionProductoDTO]
    ) -> bool: ...

    def create_preproceso(self, data: PreprocesoDTO) -> bool: ...

    def update_preproceso(self, preproceso_id: int, data: PreprocesoDTO) -> bool: ...

    def delete_preproceso(self, preproceso_id: int) -> bool: ...

    def get_all_ordenes_fabricacion(self) -> List[Any]: ...


class IMaterialService(Protocol):
    """Subconjunto de operaciones de materiales (vía `ProductService`), incluida la lectura por producto."""

    def get_materials_for_product(self, producto_codigo: str) -> List[MaterialDTO]: ...

    def get_all_materials_for_selection(self) -> List[Any]: ...

    def add_material(self, codigo: str, descripcion: str) -> Optional[int]: ...

    def link_material_to_product(self, producto_codigo: str, material_id: int) -> bool: ...

    def update_material(self, material_id: int, nuevo_codigo: str, nueva_descripcion: str) -> bool: ...

    def unlink_material_from_product(self, producto_codigo: str, material_id: int) -> bool: ...

    def delete_material(self, material_id: int) -> bool: ...
